[workspace]
resolver = "2"
members = [
    "./galvyn",
    "./galvyn-cli",
    "./galvyn-macros",
    "./galvyn-core",
    "./contrib/galvyn-contrib-auth",
    # "./contrib/galvyn-contrib-tracing",
    "./example/blog",
]

[workspace.dependencies]
axum = { version = "~0.8", default-features = false }
rorm = { version = "~0.7", default-features = false }
rorm-macro-impl = { version = "~0.9" }
