[workspace]
resolver = "2"
members = [
    "./galvyn",
    "./galvyn-cli",
    "./galvyn-core",
    "./contrib/galvyn-contrib-tracing",
    "./swaggapi",
    "./swaggapi-macro",
    "./example/blog",
]
