[workspace]
resolver = "2"
members = [
    "./galvyn",
    "./galvyn-cli",
    "./galvyn-macros",
    "./galvyn-core",
    "./contrib/galvyn-contrib-auth",
    # "./contrib/galvyn-contrib-tracing",
    "./example/blog",
]

[workspace.dependencies]
axum = { version = "~0.8", default-features = false }
rorm = { version = "*", git = "https://github.com/rorm-orm/rorm", tag = "v0.7.0-pre-3", default-features = false, features = ["postgres-only"] }
rorm-macro-impl = { version = "*", git = "https://github.com/rorm-orm/rorm", tag = "v0.7.0-pre-3" }
