[package]
name = "galvyn-contrib-settings"
version = "0.1.0"
edition = "2024"

[dependencies]
galvyn-core = { version = "*", path = "../../galvyn-core" }
rorm = { workspace = true }
thiserror = { version = "~2" }
tokio = { workspace = true, features = ["sync"] }